development:
  sessions:
    default:
      uri: mongodb://127.0.0.1:27017/pluginscan_dev

  options:
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true

test:
  sessions:
    default:
      uri: mongodb://127.0.0.1:27017/pluginscan_test

  options:
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

  options:
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true
