---
JAVA6: "1,6,0,45"
JAVA6_s: "1,6,0,45"
linux:
  chrome:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
    br_v: "23,0,1271,95"
    br_v_s: "23,0,1271,95"
  chromium:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    br_v: "22,0,1229,94"
    br_v_s: "22,0,1229,94"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
  firefox:
    ao_flash: "11,2,202,356"
    ao_flash_s: "11,2,202,356"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    br_v: "17,0,1"
    br_v_s: "17,0,1"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
ubuntu:
  chrome:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    br_v: "23,0,1271,95"
    br_v_s: "23,0,1271,95"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
  chromium:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    br_v: "22,0,1229,94"
    br_v_s: "22,0,1229,94"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
  firefox:
    ao_flash: "11,2,202,356"
    ao_flash_s: "11,2,202,356"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: ""
    ao_qt_s: ""
    ao_reader: "9,5,5"
    ao_reader_s: "9,5,5"
    ao_silver: ""
    ao_silver_s: ""
    br_v: "17,0,1"
    br_v_s: "17,0,1"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: ""
    ao_shock_s: ""
macintosh:
  chrome:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,1"
    ao_qt_s: "7,7,1"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "23,0,1271,95"
    br_v_s: "23,0,1271,95"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,4"
    ao_vlc_s: "2,1,4"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,0"
    ao_shock_s: "12,0,5,0"
  firefox:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,1"
    ao_qt_s: "7,7,1"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "17,0,1"
    br_v_s: "17,0,1"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,4"
    ao_vlc_s: "2,1,4"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,0"
    ao_shock_s: "12,0,5,0"
  safari:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,1"
    ao_qt_s: "7,7,1"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "8536,26,17"
    br_v_s: "8536,26,17"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,4"
    ao_vlc_s: "2,1,4"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,0"
    ao_shock_s: "12,0,5,0"
windows:
  chrome:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,5"
    ao_qt_s: "7,7,5"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "23,0,1271,95"
    br_v_s: "23,0,1271,95"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,146"
    ao_shock_s: "12,0,5,146"
  firefox:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,5"
    ao_qt_s: "7,7,5"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "17,0,1"
    br_v_s: "17,0,1"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,4,144"
    ao_shock_s: "12,0,4,144"
  ie:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_reader: "11,0,0"
    ao_reader_s: "11,0,0"
    ao_qt: "7,7,5"
    ao_qt_s: "7,7,5"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "10"
    br_v_s: "6"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,146"
    ao_shock_s: "12,0,5,146"
  safari:
    ao_flash: "13,0,0,206"
    ao_flash_s: "13,0,0,206"
    ao_java: "1,7,0,55"
    ao_java_s: "1,7,0,55"
    ao_qt: "7,7,5"
    ao_qt_s: "7,7,5"
    ao_reader: "11,0,06"
    ao_reader_s: "11,0,06"
    ao_silver: "5,1,20913,0"
    ao_silver_s: "5,1,20913,0"
    br_v: "7534,57,2"
    br_v_s: "7534,57,2"
    ao_dvr: 0,9,1,4
    ao_dvr_s: 0,9,1,4
    ao_vlc: "2,1,3"
    ao_vlc_s: "2,1,3"
    ao_wmp: ""
    ao_wmp_s: ""
    ao_rp: "16,0,0,282"
    ao_rp_s: "16,0,0,282"
    ao_shock: "12,0,5,146"
    ao_shock_s: "12,0,5,146"
